<?php
// Create water quality form


/**
 * Implements hook_view_data_alter().
 */
function dh_vitis_extras_views_data_alter(&$data) {

  $base = $_SERVER['DOCUMENT_ROOT'] . base_path() . drupal_get_path('module', 'dh_vitis_extras') ;
/*
  // ******************************************************
  //  Well Search Info
  // ******************************************************
  //drupal_set_message("Calling file_get_contents( " . $base . "/sql/well_search_info.sql");
  $q = "drop view if exists {view_dh_ows_wellinfo}";
  db_query($q);
  $q = file_get_contents($base . "/sql/well_search_info.sql");
  db_query($q);
  $string_cols = array('usgs_local','deq_wellno','vdh_hdin','vdh_pwsid');
  $number_cols = array('hydroid');
  $date_cols = array();
  $group_name = 'dH OWS - GWPermit Views';
  $view_name = 'view_dh_ows_wellinfo';
 
  // dh_variabledefinition to dh_feature extra join
  $data[$view_name]['table'] = array(
    'group' => $group_name,
    'title' => t($view_name),
    'help' => t($view_name)
  );
  $data[$view_name] += dh_vitis_extras_addcols($view_name, $string_cols, 'string');
  $data[$view_name] += dh_vitis_extras_addcols($view_name, $number_cols, 'numeric');
  $data[$view_name] += dh_vitis_extras_addcols($view_name, $date_cols, 'date');
  //drupal_set_message(print_r($data[$view_name],1));  
	// join to dH AdminReg Features
  $data[$view_name]['table']['join']['dh_feature'] = array(
     'left_field' => 'hydroid',
     'field' => 'hydroid'
  );
*/

}

function dh_vitis_extras_addcols($view_name, $cols, $deftype = 'string') {
  $ret = array();
  $defaults = dh_vitis_extras_coldefs();
   
  foreach ($cols as $thiscol) {
    $ret[$thiscol] = $defaults[$deftype];
    $ret[$thiscol]['title'] = "$thiscol ($view_name)";
    $ret[$thiscol]['help'] = "$thiscol ($view_name)";
    if ($deftype == 'date') {
      $ret[$thiscol]['argument']['real field'] = $thiscol;
    }
  }
  return $ret;
}


function dh_vitis_extras_coldefs() {
  $defaults = array();
  // do date setups
  $defaults['date'] = array(
    'field' => array(
    'handler' => 'views_handler_field_date',
    'click sortable' => TRUE,
    ),
    'sort' => array(
    'handler' => 'views_handler_sort_date',
    ),
    'filter' => array(
    'handler' => 'views_handler_filter_date',
    ),
    'argument' => array(
    'handler' => 'views_handler_argument_numeric',
    //'handler' => 'views_handler_argument_date',
    ),
  );
  $defaults['numeric'] = array(
    'title' => t('Numeric Field'),
    'help' => t('Numeric Field.'), // The help that appears on the UI,
    'argument' => array(
       'handler' => 'views_handler_argument_numeric',
    ),
    'field' => array(
       'handler' => 'views_handler_field_numeric',
       'click sortable' => TRUE,
    'float' => TRUE, // enables advanced formatting options
    ),
    'filter' => array(
       'handler' => 'views_handler_filter_numeric',
    ),
    'sort' => array(
       'handler' => 'views_handler_sort',
    )
  );
  $defaults['string'] = array(
      'title' => t('String Field'),
      'help' => t('String Field.'), // The help that appears on the UI,
      'argument' => array(
         'handler' => 'views_handler_argument_string',
      ),
      'field' => array(
         'handler' => 'views_handler_field',
         'click sortable' => TRUE,
      ),
      'filter' => array(
         'handler' => 'views_handler_filter_string',
      ),
      'sort' => array(
         'handler' => 'views_handler_sort',
      )
  );
  return $defaults;
}

?>